# Generated by Django 4.1.1 on 2022-09-30 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='listing_photos')),
                ('date_created', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('NONE', 'None'), ('FASHION', 'Fashion'), ('TOOLS', 'Tools'), ('TECH', 'Tech'), ('APPLIANCES', 'Appliances'), ('FURNITURE', 'Furniture'), ('TOYS', 'Toys'), ('VEHICLES', 'Vehicles'), ('REAL_ESTATE', 'Real Estate')], default='NONE', max_length=12)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
