# Generated by Django 4.1.1 on 2022-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_comment_id_comment_id_comment_comment_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
