# Generated by Django 4.1.1 on 2022-10-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_sender_comment_commenter_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
