# Generated by Django 4.1.1 on 2022-10-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
